Update frps.init

diff --git a/frps.init b/frps.init
--- a/frps.init
+++ b/frps.init
@@ -1,15 +1,13 @@
-#!/bin/bash
-
-# Startup script for frp service
-# Place in /etc/init.d and run 'update-rc.d -f frps defaults'
-# For service run: 'chkconfig --add frps'
-
+#! /bin/bash
+# chkconfig: 2345 55 25
+# Description: Startup script for frps on Debian. Place in /etc/init.d and
+# run 'update-rc.d -f frps defaults', or use the appropriate command on your
+# distro. For CentOS/Redhat run: 'chkconfig --add frps'
 #=========================================================
 #   System Required:  CentOS/Debian/Ubuntu/Fedora (32bit/64bit)
 #   Description:  Manager for frps, Written by Clang
-#   Maintainer：MvsCode
+#   Mender：MvsCode
 #=========================================================
-
 ### BEGIN INIT INFO
 # Provides:          frps
 # Required-Start:    $all
@@ -20,115 +18,147 @@
 # Description:       starts frps using start-stop
 ### END INIT INFO
 
-# Paths and variables
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-PROGRAM_NAME="Frps"
-PROGRAM_PATH="/usr/local/frps"
-SERVICE_NAME="frps"
-BIN="${PROGRAM_PATH}/${SERVICE_NAME}"
-CONFIGFILE="${PROGRAM_PATH}/frps.toml"
-SCRIPT_NAME="/etc/init.d/${SERVICE_NAME}"
-VERSION="2023"
-PROGRAM_VERSION=$("$BIN" --version)
+ProgramName="Frps"
+ProgramPath="/usr/local/frps"
+NAME=frps
+BIN=${ProgramPath}/${NAME}
+CONFIGFILE=${ProgramPath}/frps.ini
+SCRIPTNAME=/etc/init.d/${NAME}
+version="2023"
+program_version=`${BIN} --version`
 RET_VAL=0
 
-# Check if the binary exists
-[ -x "$BIN" ] || exit 0
-
-# Print the header
-print_header() {
+[ -x ${BIN} ] || exit 0
+strLog=""
+fun_clangcn()
+{
+    echo ""
     echo "+---------------------------------------------------------+"
-    echo "|     Manager for ${PROGRAM_NAME}, Author Clang, Maintainer MvsCode      |"
+    echo "|     Manager for ${ProgramName}, Author Clang, Mender MvsCode      |"
     echo "+---------------------------------------------------------+"
+    echo ""
 }
 
-# Check if the service is running
-check_run() {
-    local PID=$(pgrep -f "$BIN")
-    [ -n "$PID" ]
+fun_check_run(){
+    PID=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
+    if [ ! -z $PID  ]; then
+        return 0
+    else
+        return 1
+    fi
 }
-
-# Load the configuration file
-load_config() {
-    [ -r "$CONFIGFILE" ] || { echo "config file $CONFIGFILE not found"; return 1; }
+fun_load_config(){
+    if [ ! -r ${CONFIGFILE} ]; then
+        echo "config file ${CONFIGFILE} not found"
+        return 1
+    fi
 }
-
-start() {
-    print_header
-    if check_run; then
-        echo "${PROGRAM_NAME} (pid $PID) already running."
+fun_start()
+{
+    if [ "${arg1}" = "start" ]; then
+      fun_clangcn
+    fi
+    if fun_check_run; then
+        echo "${ProgramName} (pid $PID) already running."
         return 0
     fi
-    load_config || return 1
-    echo -n "Starting ${PROGRAM_NAME} (${PROGRAM_VERSION})..."
-    "$BIN" -c "$CONFIGFILE" >/dev/null 2>&1 &
+    fun_load_config
+    echo -n "Starting ${ProgramName}(${program_version})..."
+    ${BIN} -c ${CONFIGFILE} >/dev/null 2>&1 &
     sleep 1
-    if ! check_run; then
+    if ! fun_check_run; then
         echo "start failed"
         return 1
     fi
     echo " done"
-    echo "${PROGRAM_NAME} (pid $PID) is running."
+    echo "${ProgramName} (pid $PID)is running."
+    return 0
 }
-stop() {
-    print_header
-    PID=$(ps aux | grep frps | awk '{print $2}')
-    if [ -z "$PID" ]; then
-        echo "${PROGRAM_NAME} is not running."
-        return 0
+
+fun_stop(){
+    if [ "${arg1}" = "stop" ] || [ "${arg1}" = "restart" ]; then
+      fun_clangcn
     fi
-    echo -n "Stopping ${PROGRAM_NAME} (pid $PID)... "
-    kill $PID
-    if [ $? -eq 0 ]; then
-        echo "done"
-    else
-        echo "failed"
-        kill -9 $PID
-        if [ $? -eq 0 ]; then
-            echo "done (forced)"
+    if fun_check_run; then
+        echo -n "Stoping ${ProgramName} (pid $PID)... "
+        kill $PID
+        if [ "$?" != 0 ] ; then
+            echo " failed"
+            return 1
         else
-            echo "failed (forced)"
+            echo " done"
         fi
+    else
+        echo "${ProgramName} is not running."
+    fi
+    return 0
+}
+fun_restart(){
+    fun_stop
+    fun_start
+}
+fun_status(){
+    PID=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
+    if [ ! -z $PID ]; then
+        echo "${ProgramName} (pid $PID) is running..."
+    else
+        echo "${ProgramName} is stopped"
+        exit 0
     fi
 }
-restart() {
-    stop
-    start
+checkos(){
+    if   grep -Eqi "CentOS" /etc/issue || grep -Eq "CentOS" /etc/*-release; then
+        OS=CentOS
+    elif grep -Eqi "Debian" /etc/issue || grep -Eq "Debian" /etc/*-release; then
+        OS=Debian
+    elif grep -Eqi "Ubuntu" /etc/issue || grep -Eq "Ubuntu" /etc/*-release; then
+        OS=Ubuntu
+    elif grep -Eqi "Alpine" /etc/issue || grep -Eq "Alpine" /etc/*-release; then
+        OS=Alpine
+    elif grep -Eqi "Fedora" /etc/issue || grep -Eq "Fedora" /etc/*-release; then
+        OS=Fedora
+    else
+        echo "Not support OS, Please reinstall OS and retry!"
+        return 1
+    fi
+}
+fun_config(){
+    if [ -s ${CONFIGFILE} ]; then
+        vi ${CONFIGFILE}
+    else
+        echo "${ProgramName} configuration file not found!"
+        return 1
+    fi
+}
+fun_version(){
+    echo "${ProgramName} version ${program_version}"
+    return 0
+}
+fun_help(){
+    ${BIN} --help
+    return 0
 }
 
-status() {
-    check_run && echo "${PROGRAM_NAME} (pid $PID) is running..." || echo "${PROGRAM_NAME} is stopped"
-}
-
-config() {
-    [ -s "$CONFIGFILE" ] && vi "$CONFIGFILE" || echo "${PROGRAM_NAME} configuration file not found!"
-}
-
-version() {
-    echo "${PROGRAM_NAME} version ${PROGRAM_VERSION}"
-}
-
-help() {
-    "$BIN" --help
-}
-
-case "${1:-}" in
+arg1=$1
+[  -z ${arg1} ]
+case "${arg1}" in
     start|stop|restart|status|config)
-        "$1"
-        ;;
-    version|VERSION|-v|--version)
-        version
-        ;;
-    config|CONFIG|conf|CONF|-c|--config)
-        config
-        ;;
-    help|HELP|-h|--help)
-        help
-        ;;
+        fun_${arg1}
+    ;;
+    [vV][eE][rR][sS][iI][oO][nN]|-[vV][eE][rR][sS][iI][oO][nN]|--[vV][eE][rR][sS][iI][oO][nN]|-[vV]|--[vV])
+        fun_version
+    ;;
+    [Cc]|[Cc][Oo][Nn][Ff]|[Cc][Oo][Nn][Ff][Ii][Gg]|-[Cc]|-[Cc][Oo][Nn][Ff]|-[Cc][Oo][Nn][Ff][Ii][Gg]|--[Cc]|--[Cc][Oo][Nn][Ff]|--[Cc][Oo][Nn][Ff][Ii][Gg])
+        fun_config
+    ;;
+    [Hh]|[Hh][Ee][Ll][Pp]|-[Hh]|-[Hh][Ee][Ll][Pp]|--[Hh]|--[Hh][Ee][Ll][Pp])
+        fun_help
+    ;;
     *)
-        print_header
-        echo "Usage: $SCRIPT_NAME {start|stop|restart|status|config|version|help}"
+        fun_clangcn
+        echo "Usage: $SCRIPTNAME {start|stop|restart|status|config|version}"
         RET_VAL=1
-        ;;
+    ;;
 esac
 exit $RET_VAL
